[application]

[web.app]
base_path = "thai-pronunciation"
out_dir = "build"

# HTML title tag content
title = "thai-pronunciation"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
