name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Install Dioxus CLI from git
        run: cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli

      - name: Build project
        run: dx build --release

      - name: Copy index.html to 404.html for SPA routing
        run: cp ./build/index.html ./build/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true
